#ROS package you are documenting
package_name = "data_logger"
repo = "https://github.com/ISC-Project-Phoenix/data_logger"

#You can have multiple nodes in one package
[[nodes]]
node_name = 'data_logger'
#Relitive to this file
source_file = ['./src/data_logger.cpp']
summary = '''
Project Phoenix training data collection node. This pairs images with various car statuses and writes these to a CSV
for use as labels during NN training, then writes those images to disk as compressed jpegs.
'''

# (optional)
misc = 'see [the design for more info](https://github.com/ISC-Project-Phoenix/design/blob/main/software/ros/data_logger.md)'

#Your published topics (optional)
[[nodes.publishes]]
name = '/run_folder'
description = ' Path to the folder we are currently writing images to. That is `data_path`/something. Qos: This uses reliable transport and transient local durability'

#Your subscribed topics (optional)
[[nodes.subscribes]]
name = '/odom_ack'
description = 'AckermannDrive messages representing the current state of the kart. See design docs for info on format.'

[[nodes.subscribes]]
name = '/camera/mid/rgb'
description = 'Camera data, to be synced with training data'

#Your node parameters (optional)
[[nodes.params]]
name = 'data_path'
description = '''Directory to write data into. Note that log data will be in `data_path`/"%Y-%m-%d-%H-%M-%S"/ not in
this folder directly. Default: ./training_data'''

[[nodes.params]]
name = 'max_throttle_speed'
description = '''Velocity at which we consider the throttle fully pressed.'''

[[nodes.params]]
name = 'max_braking_speed'
description = '''Negative velocity at which we consider the brake fully pressed.'''

[[nodes.params]]
name = 'max_steering_rad'
description = ''' Max steering wheel angle, in radians. Assumed to be symmetrical.'''
